services:
  - type: web
    name: mov-o-matic-backend
    env: node
    repo: https://github.com/Vinutha017/Mov-O-Matic
    branch: main
    buildCommand: npm run build
    startCommand: npm start
    plan: starter
    autoDeploy: true
